#!/bin/bash

set -eux

# Builds local pip package repository which can then be used
# by pypi element for installing python packages
# the goal is to make sure that any openstack component in
# /opt/stack/venvs will use same version of package which was
# set in source-repository files.
function build_package(){
    REPO_PATH=$1
    cd $REPO_PATH
    [ -f setup.py ] || return 0
    python setup.py sdist
    local INFO_FILE=`ls *.egg-info/PKG-INFO`
    cp -f dist/*gz $LOCAL_PKGS_DIR
    local NAME=`grep '^Name:' $INFO_FILE|head -1|awk '{ print $2 }'`
    local VER=`grep '^Version' $INFO_FILE|head -1|awk '{ print $2 }'`
    echo "$NAME==$VER" >> $LOCAL_PIP_DIR/requirements.txt
}

function create_mirror(){
    PKG_DIR=$1
    MIRROR_DIR=$2
    [ -d $MIRROR_DIR ] || mkdir -p $MIRROR_DIR

    cat > $PKG_DIR/mirror.yaml <<EOF
cache-root: $PKG_DIR

mirrors:
 - name: openstack
   projects: []
   output: $MIRROR_DIR
EOF

    # FIXME: run-mirror expects pkgs in pip/openstack subdir
    mkdir -p $PKG_DIR/pip
    ln -s $PKG_DIR $PKG_DIR/pip/openstack

    run-mirror -b remotes/origin/master --verbose -c $PKG_DIR/mirror.yaml --no-download
}

REPO_DIR=~/.cache/image-create/repository-sources/
LOCAL_PIP_DIR=~/.cache/image-create/pip-repo
DOWNLOAD_CACHE_DIR=$LOCAL_PIP_DIR/pkgcache
LOCAL_PKGS_DIR=$LOCAL_PIP_DIR/localpkgs
PIP_MIRROR_DIR=~/.cache/image-create/pypi/mirror/

mkdir -p $LOCAL_PIP_DIR
mkdir -p $DOWNLOAD_CACHE_DIR
mkdir -p $LOCAL_PKGS_DIR
mkdir -p $PIP_MIRROR_DIR
> $LOCAL_PIP_DIR/requirements.txt

for REPO in `cat $REPO_DIR/list`; do
    [ -n "$REPO" -a -d "$REPO" ] && build_package $REPO
done

create_mirror $LOCAL_PKGS_DIR $LOCAL_PKGS_DIR/mirror
# fetch all dependencies for custom package builds
pip install -I -d $DOWNLOAD_CACHE_DIR --extra-index-url="file://$LOCAL_PKGS_DIR/mirror" -r $LOCAL_PIP_DIR/requirements.txt
# FIXME: some deps are missing:
pip install -I -d $DOWNLOAD_CACHE_DIR setuptools argparse qpid-python MySQL-python pip pbr distribute virtualenv os-apply-config
create_mirror $DOWNLOAD_CACHE_DIR $PIP_MIRROR_DIR
